# Generated by Django 4.1.7 on 2023-02-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID Пользователя в Telegram')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вес питомца')),
            ],
            options={
                'verbose_name': 'Вес питомца',
                'verbose_name_plural': 'Вес питомцев',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.weight')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время составления записи')),
                ('date_of_reception', models.DateField()),
                ('time_of_reception', models.CharField(max_length=100, verbose_name='Время записи')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('registrated', models.ForeignKey(on_delete=models.SET(0), to='user.user', verbose_name='Имя клиента')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service', verbose_name='Идентификатор услуги')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Запись',
            },
        ),
    ]
