# Generated by Django 4.1.7 on 2023-03-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registrated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Имя клиента'),
        ),
    ]
