# Generated by Django 4.1.7 on 2023-03-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('break_time_start', models.TimeField(null=True, verbose_name='Время начала перерыва')),
                ('break_time_end', models.TimeField(null=True, verbose_name='Время окончания перерыва')),
                ('vacation_date_start', models.DateField(null=True, verbose_name='Дата начала отпуска или отгула')),
                ('vacation_date_end', models.DateField(null=True, verbose_name='Дата выхода сотрудника на работу')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Специализация сотрудника', 'verbose_name_plural': 'Специализация сотрудников'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Специализация сотрудника'),
        ),
        migrations.AddField(
            model_name='category',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee', verbose_name='Имя сотрудника'),
        ),
    ]
