# Generated by Django 4.1.7 on 2023-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_employee_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vacation_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода сотрудника на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала отпуска или отгула'),
        ),
    ]
